spring.application.name=discovery-server
server.port=8761
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable compatibility verifier
spring.cloud.compatibility-verifier.enabled=false
